name: Manual Workflow

on:
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print a message
        run: echo "Workflow успешно запущен!"